docs_dir: docs/book
site_dir: docs/html
nav:
    - Home: index.md
    - v2:
        - Introduction: v2/intro.md
        - Installation: v2/installation.md
        - Usage: v2/usage.md
        - Reference:
            - Configuration: v2/configuration.md
            - "Advanced Usage": v2/advanced.md
        - 'Application Integration':
            - 'Stand-Alone': v2/application-integration/stand-alone.md
site_name: laminas-paginator
site_description: 'Paginate collections of data from arbitrary sources'
repo_url: 'https://github.com/laminas/laminas-paginator'
extra:
    project: Components
    installation:
        config_provider_class: 'Laminas\Paginator\ConfigProvider'
        module_class: 'Laminas\Paginator\Module'
    current_version: v2
    versions:
        - v2
plugins:
    - redirects:
          redirect_maps:
              intro.md: v2/intro.md
              installation.md: v2/installation.md
              usage.md: v2/usage.md
              configuration.md: v2/configuration.md
              advanced.md: v2/advanced.md
              application-integration/stand-alone.md: v2/application-integration/stand-alone.md
